# Generated by Django 5.0.6 on 2024-07-04 16:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vedaVarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='astha/')),
                ('date_add', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('ch', 'chilly'), ('sl', 'salty'), ('sp', 'spicy'), ('nr', 'normal')], max_length=2)),
            ],
        ),
    ]
