# Generated by Django 5.0.6 on 2024-07-04 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pastha', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='vedaVarity',
            new_name='PasthaVarity',
        ),
    ]
